# Generated by Django 4.1.7 on 2023-03-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_tag_remove_post_photo_alter_post_body_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
