# Generated by Django 4.1.7 on 2023-03-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_date']},
        ),
    ]
